language: node_js
node_js:
- '10'
- '9'
- '8'
- '7'
- '6'
cache:
  directories:
  - node_modules
script:
- yarn build
- yarn test
- yarn lint
deploy:
  provider: npm
  email: "$NPM_AUTH_EMAIL"
  api_key: "$NPM_AUTH_TOKEN"
  on:
    tags: true
    node_js: '8'
  skip_cleanup: true
env:
  global:
  - secure: cu84Nb1bEkb19PYpgmFd83GJ8iv4EWS3In6WiCcV5eAAQc2Ep6icthuajPHPYyE1XhD16vK0lRStUBe/lBEJv5qzCvpM7VU/1nYLosTPyK/jGa8arGS72CXtCVQePSurYhqaQe6pxYGCgJnRPGpx7El7jIsljJxjX9ZJKhL+eUBD/8zLKOJhzQ6UGoXVfERfVP2GUOgHI/bPOf1pVg/UefCcC/O4y+W1ELoyHyQuPmKVQGFzR+3zBzJvzz0Kf0NOAB3emq5+7kcHKtNrTK8z+I3xIfeqqK+B1z/b+dLXSZ5j0yW55Vdww8rpx9Ux69lq+bSOsMwJbiy+Bu4EIwMs1rJIkEFMsUUWBphI3rAZ3TUKx+EIvu/yYi9P7/ypVwnEvlNRmCcHtgvpnSkPyA2Y1ySxvY3/UshVu0uzCmrPGVlncw2y7Ic0H6ZQLei4OLf3/co5XGDmpehpqHZ5A1pPI48aawpQ/oDuxHEi1Ojz8drhwYbWz1RadzJ7/fUpbPBGixJq+Kl/70gRkHiGsjMIJzAJPQKZXjcqRgsZKrumPGMu87GWJZCH8W54VD2Mzm/jFCueNd9A2eO8DQPXf6MzCN5xsNhA3s95cEoYFtgLDJpjPRIoQcAJ03fUHaz1XTqjyIuhEcbjBwolUOPV2vLZpToQqlk/N+rWP5uOB8+M+hs=
  - secure: LYgUFQt8Mh+Wg/ofMl9peTaoo/kCu5YrHHHCh2myskb6XltYWAu2KhkcRKAq99+dreLCR1iSNHkL/wACHLVnGuqHZxAPToho039AfAIQ/r7LgLYSVbyVGRpWLE2KW0KmlD/4gP4V7gSoPwi6zbanrCsvN7rqXfv1udZLz0B5WOorqeDO3DLJw4RnvCL9dSMmI2sBYS1nHnt4GdSDl8+p79pRUvT5rTWIgn57f2NEiXBEDQ4PWbAfUIIQMsIm+o+6Q42kp4nXWW6IObybOCip/reyuytKUGYZ62o9qDQhvFn+3YyOBngsGdRUkz3XpzIPvUtj9omADY4SRG44ebS+/YRmvwzXC72byVeE9XQMREO0g3uhxQ78Q1U/KC3D5C9+230qXnKNDIW/qWg7z1BVZrHnyvf43wAqs+CLo+vlHQqD58EbCptY7uLN1Xj8BN68cQ0+0xr6ZI0bk5+ceo8QWufaJySKVbarqYWG+nv/SIMnPvPV/4yJlIo3UUqYuMyBol01g6I/BIR+ssZqMWLe+wV/Ju4+dcghSuzoekYiwCja6rZ6bUtQ1DvrdJrQ3cj24r5QuNtYot5oF64w5vPFLD6jJKjZkI/niJHgWrI9XfoKIvarsRbh3ymrTrPALWR/yCa63DcTEujX7uQwy4TI7+cgYCndtYPf0fI9IBkIgu4=
